# Generated by Django 5.0.6 on 2026-07-22 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_id', models.UUIDField()),
                ('buyer_id', models.UUIDField()),
                ('seller_id', models.UUIDField()),
                ('type', models.CharField(choices=[('message', 'Message'), ('viewing_request', 'Viewing request'), ('offer', 'Offer')], default='message', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('closed', 'Closed')], default='open', max_length=20)),
                ('message', models.TextField()),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('requested_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['buyer_id'], name='inquiries_i_buyer_i_e48745_idx'), models.Index(fields=['seller_id'], name='inquiries_i_seller__a081d7_idx'), models.Index(fields=['property_id'], name='inquiries_i_propert_f6d67b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiries.inquiry')),
            ],
        ),
    ]
